name: CI with Caching

on:
  push:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  build-with-cache:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up uv
        uses: astral-sh/setup-uv@v5
        
      - name: Create and Activate Virtual Environment
        # This step creates the .venv directory
        run: uv venv
        
      - name: Cache uv dependencies
        uses: actions/cache@v4
        id: cache-uv # ID is necessary to check the output status
        with:
          path: ~/.cache/uv 
          # 🎯 STATIC KEY: Required for validation check
          key: cache-a70524d 

      - name: Install dependencies
        # Fix for the "File not found" and "uv not found" errors
        run: |
          # The requirements.txt file must exist in the repo root
          source .venv/bin/activate
          uv pip install -r requirements.txt
        
      - name: prime-cache-a70524d
        # Check the cache status using the output of the 'cache-uv' step
        run: |
          if [[ "${{ steps.cache-uv.outputs.cache-hit }}" == "true" ]]; then
            echo "Cache hit! Dependencies were restored."
          else
            echo "Cache miss. Dependencies were installed and cache will be saved."
          fi
