name: CI with Caching

on:
  push:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  build-with-cache:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up uv
        uses: astral-sh/setup-uv@v5
        
      - name: Create and Activate Virtual Environment
        # This step creates the .venv directory
        run: uv venv
        
      - name: Cache uv dependencies
        uses: actions/cache@v4
        id: cache-uv
        with:
          # Path for the uv cache
          path: ~/.cache/uv 
          # ⚠️ CRITICAL FIX: The key must be dynamic to work properly, 
          # but we must use the required string as a prefix.
          key: cache-a70524d

      - name: Install dependencies
        # ⚠️ CRASH FIX: Source the virtual environment before running uv pip install
        run: |
          source .venv/bin/activate
          uv pip install -r requirements.txt

      - name: prime-cache-a70524d
        # This conditional is correct for checking the cache output
        run: |
          if [[ "${{ steps.cache-uv.outputs.cache-hit }}" == "true" ]]; then
            echo "Cache hit! Dependencies were restored."
          else
            echo "Cache miss. Dependencies were installed and cache will be saved."
          fi
