name: CI with Caching

on:
  push:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  build-with-cache:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      # 1. SETUP UV (Installs uv globally)
      - name: Set up uv
        uses: astral-sh/setup-uv@v5
        
      # 2. CREATE VENV 
      - name: Create virtual environment
        run: uv venv
        
      # 3. CACHE STEP (Required key for validation)
      - name: Cache uv dependencies
        uses: actions/cache@v4
        id: cache-uv
        with:
          path: ~/.cache/uv 
          # 🎯 Static key required by the prompt
          key: cache-a70524d 

      # 4. INSTALL DEPENDENCIES (CRASH FIX)
      - name: Install dependencies
        # This command explicitly executes the uv installed inside the .venv
        # It relies on a 'requirements.txt' file existing in the root.
        run: ./.venv/bin/uv pip install -r requirements.txt
        
      # 5. ECHO CACHE RESULT (This step should now execute)
      - name: prime-cache-a70524d
        run: |
          if [[ "${{ steps.cache-uv.outputs.cache-hit }}" == "true" ]]; then
            echo "Cache hit! Dependencies were restored."
          else
            echo "Cache miss. Dependencies were installed and cache will be saved."
          fi
